apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # The name of the ClusterRole
  name: grafana-secret-list
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]
