apiVersion: v1
data:
  passwordKey: cGFzc3dvcmQ=
  userKey: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2024-11-21T09:10:23Z"
  name: grafana-secret
  namespace: default
  resourceVersion: "126069"
  uid: ae7b5685-8022-486f-aa62-5a60f104078d
type: Opaque