apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-sql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/Kubescape_scan_results/nsa_results.json
